linters:
  disable:
    - lll
    - gocritic
    - wsl
    - gomnd
    - goerr113
    - testpackage
  enable-all: true
linters-settings:
  goimports:
    local-prefixes: github.com/risentveber/yaml-matrix