version: '2'

tasks:
  coverage:
    desc: 'Run tests with coverage and open report in default browser'
    cmds:
      - go test -coverprofile=./tmp/cover.out ./...
      - go tool cover -html=./tmp/cover.out -o ./tmp/cover.html
      - open ./tmp/cover.html
  attach_hooks:
    desc: "Attach git hooks"
    cmds:
      - cp ./tools/pre-commit.sh ./.git/hooks/pre-commit
      - cp ./tools/pre-push.sh ./.git/hooks/pre-push
      - chmod 777 ./.git/hooks/pre-commit
      - chmod 777 ./.git/hooks/pre-push
  build:
    desc: "Build cli tool"
    cmds:
      - go build -o ./cmd/cli/cli.bin ./cmd/cli
  lint:
    desc: "Run linter"
    cmds:
      - golangci-lint run ./...
  test:
    desc: "Run tests"
    cmds:
      - go test ./...